### PR TITLE
Feature/Python3 & Windows10 compatibility

### PR DESCRIPTION
**Pull request by nklapste**
Migrating code to work for Python3. This drops Python2 support.

Adding support to execute within a windows environment.

Fixing path specifications to have better support on windows.

Tested with a `tensorflow==2.0.0` backend on a windows 10 machine.
**Features:**
* Python3 compatibility
* Windows 10 compatibility
* tensorflow 2 compatibility
* `scripts/download_weights.py` is now system agnostic by using requests
* `.travis.yml` build now tests on windows 10, osx, and linux

**TODO:**
* some changes regarding updates to `keras` and `tensorflow` might have changed behavior with using the prebuilt `deepmoji_weights.hdf5` model 
  * test `test_finetuning.test_encode_texts` is raising a `AssertionError` as its `avg_across_sentances` is `[-0.024  0.027 -0.046 -0.002 -0.   ]` instead of test's expected `[-0.023, 0.021, -0.037, -0.001, -0.005]`
* code within `examples` has not been heavily tested or validated on windows 10
* verify `scripts/analyze_all_results.py`
* verify `scripts/analyze_results.py`

### CODE REVIEW

**Comment by bfelbo** [comment]
Amazing, thank you for working on this! 🙌

**Comment by nklapste** [comment]
@bfelbo are you comfortable with dropping Python2.7 support? Maybe locking the python2.7 version in another branch or tag?

Otherwise, I could look into making this cross-compatible with python2.7 and python3+, but, in my experience this leads to messy code.

**Comment by bfelbo** [comment]
Completely agree. Let’s drop 2.7 and make a new tag/release.

Similarly, I’ve been thinking of upgrading the code to TF2 and dropping support for TF1. It requires converting the pretrained model to TF2, but that hopefully shouldn’t be too hard.

**Comment by bfelbo** [comment]
Feel free to add a line to the README that you added Python3 support :)

**Comment by nklapste** [comment]
@bfelbo For verifying `scripts/analyze_all_results.py` and `scripts/analyze_results.py` both require `<dataset>_<method>_results.txt` files. I sadly cannot find those files. Are these generated somehow or located in the repo?

**Comment by bfelbo** [comment]
I’ll look into this over the weekend.

**Comment by nklapste** [comment]
I would further refactor this PR, but, I feel that this would complicate things for review. Would it be possible for you to review the functionality of this PR and maybe make a refactoring/cleanup PR afterwards?

**Comment by nklapste** [comment]
Besides some refactoring, this PR should be ready for review. 

However the following scripts could not be verified to work by me `scripts/analyze_all_results.py`
and `scripts/analyze_results.py`

**Comment by bfelbo** [comment]
Thank you Nathan. I'll take a look on the weekend :)

**Comment by bfelbo** [comment]
Looking at it now. There's a lot of changes so it might take some time.

**Comment by bfelbo** [comment]
Thanks for this PR. It's clear that you've put a lot of effort into this.

I've been trying to review this, but it's hard as there's a lot of other changes to the code besides adding Python3 / Windows compatibility. A few examples:
- Travis setup
- .gitignore changes
- New get_vocabulary() function, which is used in all examples
- Linting changes (import order, indenting, line breaks)
- Removing the os.path logic to simplify where the code can be called from

Some of these changes might be useful, but it'd be great if they could be submitted as separate pull requests after moving the codebase to Python3. The smaller the pull request, the easier it is to review/merge it :)

Can you update this PR (or create a new one) to contain only the minimal changes needed for Python3 support?

That'd be amazing.

**Comment by bfelbo** [comment]
If I try to run `python3 score_texts_emojis.py` with the code in this PR, I get the error `ModuleNotFoundError: No module named 'create_vocab'`. If you remove all the non-essential changes from this PR, then it'll also be less likely to break the code :)

**Comment by nklapste** [comment]
I'll minify this PR to is base elements! Thanks for your initial reviews!

**Comment by nklapste** [comment]
> 
> 
> If I try to run `python3 score_texts_emojis.py` with the code in this PR, I get the error `ModuleNotFoundError: No module named 'create_vocab'`. If you remove all the non-essential changes from this PR, then it'll also be less likely to break the code :)

Have you installed the deepmoji project locally? 

Running the following command:
```console
pip install . 
```
Within the project directory should install deepmoji to your python environment. Afterwards, you should be able to import `deepmoji.*` modules without issues.

Within my installed deepmoji environment I'm able to run `python score_texts_emojis.py`.

**Comment by nklapste** [comment]
PR continued on with #53 closing this bloated PR

**Pull request closed without merging**
