### PR TITLE
Add Travis CI file

### PR DESCRIPTION
**Pull request by rht**
The tests are failing because perhaps the `tensorflow` version needs to be pinned.
See https://travis-ci.org/rht/DeepMoji.

### CODE REVIEW

**Comment by bfelbo** [comment]
Thanks. Yes, this does indeed seem to be because of the newest tensorflow version (see https://github.com/fchollet/keras/issues/7736). Can you in this PR also change Keras to 2.0.9 in `setup.py` and check that nothing is failing?

**Comment by rht** [comment]
@bfelbo I have reduced the err count to 1 with keras==2.0.9 and tensorflow==1.4.0. The error persists when I tried the permutation of [keras==2.0.7, keras==2.0.9] x [tensorflow==1.3.0, tensorflow==1.4.0].
Any idea of what went wrong?

**Comment by rht** [comment]
https://travis-ci.org/rht/DeepMoji/builds/298894532

**Comment by rht** [comment]
(also, I will follow-up this PR with one that does macOS testing and another for PEP8 check cleanup)

**Comment by rht** [comment]
Wait, it actually passed ! The Travis URL I told at ^ (https://travis-ci.org/rht/DeepMoji/builds/298894532)

**Comment by bfelbo** [comment]
Looks good! I'll merge.

**Comment by bfelbo** [comment]
Btw., sounds great with macOS testing and PEP8!

**Pull request merged**
