### PR TITLE
Add optional return_attention param to model

### LINKED ISSUE #4: Attention weights
Do you have a preferred/recommended way of exposing the attention weights at inference-time for visualizing the words/timesteps that were most heavily weighted for the prediction with this Keras implementation?

### PR DESCRIPTION
**Pull request by ryanleary**
This PR adds the ability to return attention mechanism weights from the AttentionWeightedAverage layer and the full DeepMoji model. In the latter case, the weights are exposed as another model output for easy integration.

Closes #4.

### CODE REVIEW

**Comment by bfelbo** [comment]
Thanks for this. Can you comment on why you add the attention weights as part of the same output instead of as a separate output? That seem a bit hacky to me and requires the need for the additional 'slice' methods etc. I think it would be much simpler if the attention layer just returns two outputs (original + attention map).

Please remember to add unit tests when you add new functionality. Thanks!

**Comment by ryanleary** [comment]
I see a clear way to add outputs to models (as I did) but not a clear way to return multiple tensors from a layer. Returning a tuple in the `call` function didn't seem to work. If you know of a better way offhand, I'm happy to do it. I agree it's a bit hacky as-is. Unfortunately, I'm not very familiar with Keras -- I work predominantly with pytorch.

Will go back and add unit tests as well once we figure out the preferred approach for returning the attention vector.

**Comment by ryanleary** [comment]
I will give the suggestions in this keras thread https://github.com/fchollet/keras/issues/3061 a try.

**Comment by bfelbo** [comment]
Sounds good. If you feel like implementing DeepMoji in pytorch instead, then that's also highly encouraged and appreciated :)

**Comment by ryanleary** [comment]
@bfelbo Pushed requested changes (turns out you can return a _list_ but not a _tuple_ of tensors). Also added a test. Let me know if there's anything else you'd like to see.

A PyTorch implementation may come at some point, but I don't have the cycles at the moment. Thanks for your work on this, it's a great paper -- really well done -- and the code is well structured and commented. Certainly a nice surprise!

**Comment by bfelbo** [comment]
@ryanleary Thanks for your kind words and your nice PR. I hope our code/model will be useful - let me know if you have any questions!

**Comment by bfelbo** [comment]
@ryanleary If you have the time, it would be amazing to have an example that extracts the attention weights and visualizes them. For instance, the visualization could be a 1D version of [this](https://cdn-images-1.medium.com/max/1800/1*tLu7M_LyqWfXIaikRJWGFg.png) ([code here](https://medium.com/datalogue/attention-in-keras-1892773a4f22)), where the words are printed next to the attention weights.

**Comment by un-lock-me** [comment]
Wow this feature is exactly what I needed, thanks a lot!

**Pull request merged**
